- hosts: webservers
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install PHP
      apt:
        name: php-fpm
        state: present
